version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: mydb
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

  java-app:
    build:
      context: ./java-app
    container_name: my_java_app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres_user
      DB_PASSWORD: postgres_password
      DB_NAME: mydb
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
